version: '3.8'

services:
  reddit-url-summarizer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
      - "8000:8000"
    volumes:
      - .env:/app/.env
    environment:
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_USER_AGENT=${REDDIT_USER_AGENT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
